# Generated by Django 4.2.5 on 2024-03-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='floor_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='house_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='house_type',
            field=models.CharField(blank=True, choices=[('Bunglow', 'Bunglow'), ('Duplex', 'Duplex'), ('Flat', 'Flat'), ('Normal', 'Normal')], max_length=15, null=True),
        ),
    ]
