# Generated by Django 4.2.5 on 2024-03-14 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_advisorslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorslot',
            name='booked_user_list',
            field=models.ManyToManyField(null=True, related_name='booked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advisorslot',
            name='max_user',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='advisorslot',
            name='pending_user_list',
            field=models.ManyToManyField(null=True, related_name='pending_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
