# Generated by Django 4.2.6 on 2024-04-22 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0005_auctionitem_approval_status_auctionitem_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='floor_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='house_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='house_type',
            field=models.CharField(blank=True, choices=[('Bunglow', 'Bunglow'), ('Duplex', 'Duplex'), ('Flat', 'Flat'), ('Normal', 'Normal')], max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='AdvisorSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('max_user', models.IntegerField(default=10)),
                ('total_user', models.IntegerField(blank=True, default=0, null=True)),
                ('meet_link', models.CharField(blank=True, max_length=300, null=True)),
                ('booked_user_list', models.ManyToManyField(blank=True, related_name='booked_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
