# Generated by Django 4.2.5 on 2024-03-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_advisorslot_booked_user_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorslot',
            name='total_user',
            field=models.IntegerField(default=0),
        ),
    ]
