# Generated by Django 5.0.2 on 2024-03-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_advisorslot_pending_user_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorslot',
            name='total_user',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
