# Generated by Django 4.2.7 on 2024-02-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer_seller',
            name='email',
        ),
    ]
