# Generated by Django 4.2.6 on 2024-03-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_remove_buyer_seller_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_seller',
            name='ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
