# Generated by Django 4.2.6 on 2024-03-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_buyer_seller_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer_seller',
            name='ratings',
        ),
        migrations.AddField(
            model_name='buyer_seller',
            name='ratings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buyer_seller',
            name='ratings_sum',
            field=models.IntegerField(default=0),
        ),
    ]
