# Generated by Django 4.2.6 on 2024-04-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auctionitem_approval_status_auctionitem_winner_and_more'),
        ('userProfile', '0004_remove_buyer_seller_ratings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('buyer_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.buyer_seller')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.auctionitem')),
            ],
            options={
                'unique_together': {('buyer_seller', 'item')},
            },
        ),
    ]
